### ISSUE TITLE
ImportError: /anaconda3/envs/diffbindfr_env/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so: undefined symbol: iJIT_NotifyEvent

### ISSUE THREAD

**Issue by masterwhook** [HBioquant/DiffBind#10]
Hi, 
when running  python DiffBindFR/app/predict.py -h , import issue happend
 
Traceback (most recent call last):
  File "/DiffBindFR/DiffBindFR/app/predict.py", line 12, in <module>
    import torch
  File "/anaconda3/envs/diffbindfr_env/lib/python3.9/site-packages/torch/__init__.py", line 218, in <module>
    from torch._C import *  # noqa: F403
ImportError: /anaconda3/envs/diffbindfr_env/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so: undefined symbol: iJIT_NotifyEvent

it looks like some link missing about libtorch_cpu.so with from “ldd -r /anaconda3/envs/diffbindfr_env/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so”.

could you give some suggestions how to fix this. Thanks in advance.

**Comment by Daisyli95** [comment]
I met the same problem when creating an virtual environment using the command "conda env create -f env.yaml".  Instead of using the env.yaml file, I tried to install the pytorch and cuda first by using 
1. conda install pytorch==1.13.1 torchvision==0.14.1 torchaudio==0.13.1 pytorch-cuda=11.7 -c pytorch -c nvidia
and then 
2. conda env update -f env.yaml --prune 
to install other packages.

This solved the problem.

**Comment by HBioquant** [comment]
Thanks for @Daisyli95’s help, I will close this issue channel.
