### ISSUE TITLE
Ca2+ ions. scoring functions

### ISSUE THREAD

**Issue by CLG68** [HBioquant/DiffBind#5]
Dear Dr Zhu,

I did a few tests.  One of my targets has a C2+ ion in the binding pocket that has been shown, in co-crystals, to be important for binding. The receptor models I get from a docking with DiffBindFR seem to be stripped of Hydrogen, water molecules and ions.  Probably it is a limitation of this approach.  Still, the binding pose of the co-crystallized ligands look very similar than with the co-crystal.  However, not having a Ca2+ there could be affecting the scoring of the different poses.  I just wanted to double check with you if it were possible to keep the Ca2+.

Anyways, most of my targets do not have ions in the binding pocket so DiffBindFR will still be very useful.

From my tests, I think smina scoring works much better than mdn.  I don't think I'm going to rely on mdn.

In term of speed, at 40 poses/ligand, it takes about 2min/ligand. If I increase too much -bs, I get a problem with Pytorch vs available memory on the GPU and if I increase too much -cpu, the script crashes.  I found a sweet spot that seem to work well.  For screening big libraries, a few seconds here and there make a huge difference at the end.  Do you have any suggestions? 

Thanks for help,
Christian

**Comment by HBioquant** [comment]
Hi, Christian,

Thank you for your detailed feedback and for testing DiffBindFR.

Regarding your first question, to the best of my knowledge, most current deep learning methods do not consider cofactors and important crystal waters in the pocket environment due to numerous technical and data difficulties. Therefore, for fair comparison, we did not further consider these when building the model. Moreover, it's worth emphasizing that DiffBindFR is entirely focused on the setting of flexible docking, which requires remodeling the conformation of the pocket.  If these factors are to be considered, I believe it would be necessary to reconstruct these ingredients. This is something we are planning to do in the future, as it involves mining more data and considering how to identify which water molecules and metal ions participate in important interactions. I am fully aware that this is important for biomolecular recognition, and the AI-docking models need to consider these to enhance the interpretability of physical interactions. 

Since the protein conformation is reconstructed, the hydrogen atoms will also be removed, as the DiffBindFR may model a different binding environment. **Here, I strongly suggest that users who need this can re-parameterize the force field of the sampled binding conformation to explain more detailed interactions**, such as using Schrodinger software or ChimeraX, or even using the [pl.py](https://github.com/HBioquant/DiffBindFR/blob/main/DiffBindFR/relax/pl.py) I provided to do force field parameterization.

Regarding MDN not meeting your expectations, I guess the tests you are doing now are redocking, which we have reported in our paper that smina performs slightly better than MDN under redocking. However, MDN performs better in more realistic cross-docking scenarios, which may still require case-by-case analysis.

As for speed, I greatly appreciate your pointing it out. There was a small mistake here for me, and I have [fixed this bug](https://github.com/HBioquant/DiffBindFR/commit/be7a2ee464849620200024def3f350a3233a0096) (it only affects the speed of program execution). Now you can try to fully utilize your CPU to process data. Another factor affecting speed is your graphics card resources. I have tested Tesla v100-32GB and GeForce RTX 3090 (both batch size and CPU are 16), and each pair takes an average of 52s. Another way to speed up is to use the [slurm job array to submit multiple nodes](https://github.com/HBioquant/DiffBindFR?tab=readme-ov-file#userdefine), as I wrote in the README.

Best,
Jintao Zhu

**Comment by CLG68** [comment]
Thank you very much for your feedback and the correction.  I was running at -cpu 8 -bs 10; I think 52s on a better hardware is similar to what I get, I just wanted to be sure I was not completely off because of some configuration. I realize that going flexible on prt + ligand cannot be fast.  To shrink my library, I'm using BANANA (6M cmpds/h) and a negative-image + ShaEP (1.5M structures/h) to I get down to 350k while still keeping 75% of the positive controls but I cannot rely on poses from ShaEP.  I was really impressed by the poses I got with DiffBindFR.  However, I'll need to switch to an HPC as 350k @ 1min would take months to get through.  I just wanted to be sure that everything works fine locally before migrating to an HPC.

I still have to try pl.py.

Again, thank you very much for your help and patience with all my questions,
Best,
Christian

**Comment by CLG68** [comment]
There seems to be mostly no correlation with Smirna and MDN scoring.  I'm not expecting that they would give exactly the same ranking but still I would not use MDN for a consensus with Smirna.  I'm currently exploring other scoring functions such as Genscore, IGModel and AA-score to get better correlations.  Maybe there is something wrong with my MDN installation.  However, Smirna works very well.

Best,
Christian
